name: BookTrackerIOS
options:
  bundleIdPrefix: com.booktracker
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: en
  xcodeVersion: "15.2"

packages:
  CoreDomain:
    path: Packages/CoreDomain
  Application:
    path: Packages/Application
  InfrastructureIOS:
    path: Packages/InfrastructureIOS

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    ENABLE_PREVIEWS: true
    SWIFT_EMIT_LOC_STRINGS: true

targets:
  BookTrackerApp:
    type: application
    platform: iOS
    sources:
      - path: BookTrackerApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.booktracker.ios
        INFOPLIST_FILE: BookTrackerApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_ASSET_PATHS: '"BookTrackerApp/Preview Content"'
    dependencies:
      - package: CoreDomain
      - package: Application
      - package: InfrastructureIOS
    scheme:
      testTargets:
        - BookTrackerAppTests
      gatherCoverageData: true

  BookTrackerAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BookTrackerAppTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        PRODUCT_BUNDLE_IDENTIFIER: com.booktracker.ios.tests
    dependencies:
      - target: BookTrackerApp
      - package: CoreDomain
      - package: Application
      - package: InfrastructureIOS

schemes:
  BookTrackerIOS:
    build:
      targets:
        BookTrackerApp: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - BookTrackerAppTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
